# Generated by Django 2.2.8 on 2020-02-29 01:41

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_race24", models.BooleanField()),
                ("coins", django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ("bet_amount", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "win_amount",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("win_bet_paid", models.BooleanField(default=False)),
                ("win_points", models.PositiveIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "game_bets"},
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_wins_count", models.PositiveIntegerField(default=0)),
                ("car_wins_roi_avg", models.FloatField(default=0)),
                ("car_wins_total_points", models.PositiveIntegerField(default=0)),
                (
                    "car_wins_total_amount",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("bought", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "game_cars"},
        ),
        migrations.CreateModel(
            name="CarShowroom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_model", models.PositiveSmallIntegerField(default=0)),
                ("car_boost", models.FloatField(default=0)),
                (
                    "car_extras",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                ("car_price", models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={"db_table": "game_car_showrooms"},
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_race24", models.BooleanField(db_index=True, default=True)),
                ("race_amount", models.DecimalField(decimal_places=6, max_digits=10)),
                ("players", models.PositiveIntegerField(default=0)),
                ("race_hash", models.CharField(max_length=128)),
                ("start", models.DateTimeField(null=True)),
                (
                    "start_coins_price",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                ("race_duration_seconds", models.SmallIntegerField(default=7200)),
                ("finish", models.DateTimeField(null=True)),
                (
                    "finish_coins_price",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                (
                    "coins_performance",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                (
                    "cars_performance_at_finish",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                ("err_prolonged_game", models.BooleanField(default=False)),
                ("err_prolonged_game_time_delta", models.IntegerField(default=0)),
                ("wins_paid", models.BooleanField(default=False)),
            ],
            options={"db_table": "game_races"},
        ),
        migrations.CreateModel(
            name="RaceIndexer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bounty_index", models.SmallIntegerField(default=0)),
            ],
            options={"db_table": "game_race_indexer"},
        ),
        migrations.CreateModel(
            name="RacingTeam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "base_coins_portfolio",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                (
                    "cost_to_join_in",
                    models.DecimalField(decimal_places=6, default=5, max_digits=10),
                ),
            ],
            options={"db_table": "game_racing_teams"},
        ),
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prices",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                (
                    "epoch_prices",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "game_tickers"},
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="likes",
                        to="game.RacingTeam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "game_team_members"},
        ),
        migrations.CreateModel(
            name="RaceRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("race_type", models.SmallIntegerField()),
                ("coins", django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ("is_race24", models.BooleanField()),
                ("bet_request_fullfiled", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "bet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.Bet",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="game.Car"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "game_race_registrations"},
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("module", models.CharField(max_length=128)),
                ("message", models.CharField(max_length=512)),
                ("is_new", models.BooleanField(default=True)),
                ("seen_by_user_on", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "game_notifications"},
        ),
        migrations.AddField(
            model_name="car",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="game.CarShowroom"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="bet",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="game.Car"
            ),
        ),
        migrations.AddField(
            model_name="bet",
            name="race",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="game.Race"
            ),
        ),
        migrations.AddField(
            model_name="bet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
