# Generated by Django 2.2.10 on 2020-03-02 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="This is used for internal reference.",
                    ),
                ),
                ("affiliate_slug", models.SlugField(max_length=200, unique=True)),
                ("referral", models.CharField(blank=True, max_length=200)),
                (
                    "credit",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "total_bet_amount",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("total_win_points", models.PositiveIntegerField(default=0)),
                (
                    "total_win_amount",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("is_robot", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("likes", models.PositiveSmallIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "profiles_profiles"},
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "liked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "profiles_likes"},
        ),
        migrations.CreateModel(
            name="Affiliate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "affiliate",
                    models.OneToOneField(
                        help_text="The user who uses affiliate link.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affiliate_with",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The owner of the affiliate link.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affiliates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "profiles_affiliate"},
        ),
    ]
