# Generated by Django 2.2.10 on 2020-03-02 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IoiUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=128)),
                ("jwt_secret", models.UUIDField(default=uuid.uuid4)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_investor", models.BooleanField(default=False)),
                ("created", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "IOI user",
                "verbose_name_plural": "IOI users",
                "db_table": "users_users",
            },
        )
    ]
